cypress/fixtures/chooserSeed.json, cypress/integration/DoenetChooser/DoenetChooser.spec.js, cypress_php/api/cleanupChooser.php, cypress_php/api/setupChooser.php, src/React/DoenetBranchBrowser.js, src/React/DoenetChooser.js, src/React/branchBrowser.css, src/React/chooser.css, static/api/loadAllBranches.php, static/api/saveFolder.php
Modified the rules and structure for content and folders
=> Dev chooser reconfig

package.json, src/Doenet/components/templates/ReadMe.md, src/Doenet/components/templates/allOptions.js, src/Doenet/components/templates/childlogic.js, src/Doenet/components/templates/inheritOnly.js, src/Doenet/components/templates/inputComponent.js, src/React/header.css, src/test/index.html
Also pointer cursor over logo to go to home page
=> /test without DoenetAPI and Component Creation Documentation

src/React/DoenetChooser.js
Fix chooser rendering before all content are fully loaded.
=> Fix chooser async

src/React/DoenetCourse.js, src/React/DoenetHeader.js, src/React/header.css, src/React/menu.css, src/React/menu.js, src/React/menuItem.css, src/React/menuItem.js, static/api/roles.php
Course selector minor bug: selected course does not appear to be the first item in menu. Course selector will be moved to course so I will resolve it later. Tools seems working fine
=> Integration01

src/React/DoenetCourse.js, src/React/Selector/SelectionSet.js, src/React/menu.js, src/React/menuItem.css, src/React/menuItem.js
=> layout integration for course and SelectionSet

dist/api/sendSignInEmail.php, dist/api/signInEmail.html, src/imports/PanelHeaderComponents/Menu.js, src/imports/PanelHeaderComponents/MenuItem.js, src/imports/PanelHeaderComponents/SectionDivider.js, static/api/sendSignInEmail.php, static/api/signInEmail.html
New HTML version of the sign in email
=> Pretty PHP Email, Menu, MenuItem, SectionDivider

src/Doenet/renderers/css/textinput.css, src/Renderers/mathinput.js
=> <mathinput /> Updates

cypress/integration/answerValidation/matchpartial.spec.js, cypress/integration/assignNames/basiccopy.spec.js, cypress/integration/assignNames/collections.spec.js, cypress/integration/tagSpecific/feedback.spec.js, cypress/integration/tagSpecific/point.spec.js, cypress/integration/tagSpecific/problem.spec.js, cypress/integration/tagSpecific/sectioning.spec.js, cypress/integration/variants/specifyingsubvariants.spec.js, src/Doenet/components/Function.js, src/Doenet/components/Math.js, src/Doenet/components/Substitute.js, src/Doenet/components/abstract/SectioningComponent.js, src/Doenet/utils/checkEquality.js, src/Doenet/utils/math.js, src/chooser/index.html, src/controls/index.html, src/course/index.html, src/dashboard/index.html, src/docs/index.html, src/dragdrop/index.html, src/exam/index.html, src/exampletool/index.html, src/guesteditor/index.html, src/home/index.html, src/library/index.html, src/page/index.html, src/temp/index.html, src/test/index.html
=> MathJax doesn't use $$ as delimiters

src/Tools/DoenetLibrary.js, src/imports/Drive.js, static/api/addDrive.php
=> Create Course Error Handling and Toast

cypress/integration/tagSpecific/answer.spec.js, src/Core/Core.js, src/Core/Dependencies.js, src/Core/components/Answer.js, src/Core/components/Award.js, src/Core/utils/serializedStateProcessing.js
=> use immediateValue for submit buttons

cypress/integration/tagSpecific/sidebyside.spec.js, src/Core/components/Embed.js, src/Core/components/Graph.js, src/Core/components/Image.js, src/Core/components/Slider.js, src/Core/components/Video.js, src/Viewer/renderers/embed.jsx, src/Viewer/renderers/graph.jsx, src/Viewer/renderers/image.jsx, src/Viewer/renderers/sideBySide.jsx, src/Viewer/renderers/utils/css.js, src/Viewer/renderers/video.jsx
=> sizeToCSS util converts component size for renderers

src/Tools/_framework/NewToolRoot.jsx, src/Tools/_framework/Panels/MenuPanels.jsx, src/Tools/_framework/Profile.jsx
Profile picture lines up when closed and menu panel header position fixed when scrolling
=> fixed menu panel header

src/Tools/_framework/NewToolRoot.jsx, src/Tools/_framework/ToolHandlers/CourseToolHandler.jsx, src/Tools/_framework/ToolPanels/DriveCards.jsx, src/Tools/_framework/ToolPanels/DrivePanel.jsx
=> Autogenerated url on recoil changes; Recoil Updates on url changes

src/Tools/_framework/EnterLeave/NavigationLeave.jsx, src/Tools/_framework/NewToolRoot.jsx, src/Tools/_framework/ToolPanels/DrivePanel.jsx
=> onLeave tool

src/Api/moveItems.php, src/Tools/_framework/ToolPanels/NavigationPanel.jsx, src/_reactComponents/Drive/NewDrive.jsx
Added more robust failure message and and "isViewOnly" boolean flag for drive. The flag is on when the view is set to student, and this behavior should be updated for more nuance in the future.
=> isViewOnly flag for Drive

src/Api/loadFolderContent.php, src/Tools/_framework/ToolPanels/NavigationPanel.jsx
=> files only show if children are present

src/Tools/_framework/ToolPanels/HomePanel.jsx
Images should not be imported into the JS file due to server side MIME type settings, instead use a source URL in your image or file tag
=> use url instead of import

src/Api/jwt.php, src/Tools/_framework/ToolPanels/AccountSettings.jsx, src/Tools/_framework/ToolPanels/SignIn.jsx, src/Tools/_framework/ToolPanels/SignOut.jsx
added a temp signout button in settings and a "go home" button at the signout page
=> sign in/out redirects

src/Api/removeCollectionEntry.php, src/Api/updateCollectionEntryVariant.php, src/Tools/_framework/ToolPanels/CollectionEditor.jsx
my flag was inverted, this is for pushing to production ASAP
=> FIX: collections load bug & edit permissions

cypress/integration/DoenetML/tagSpecific/function.spec.js, cypress/integration/DoenetML/tagSpecific/mathlist.spec.js, cypress/integration/DoenetML/tagSpecific/textlist.spec.js, src/Core/Core.js, src/Core/components/BooleanList.js, src/Core/components/Function.js, src/Core/components/MathList.js, src/Core/components/TextList.js
lists don't require descendants have replacements
=> bug fixes: extrema of interpolated functions

src/Core/Core.js, src/Core/utils/returnAllPossibleVariants.js, src/Tools/_framework/ToolPanels/AssignmentViewer.jsx, src/Viewer/DoenetViewer.jsx
=> Fixed Keyboard for assignments

src/Core/Core.js, src/Core/components/Point.js, src/Core/components/Vector.js, src/Viewer/DoenetViewer.jsx, src/Viewer/renderers/point.jsx, src/Viewer/renderers/vector.jsx
reload renderer state while core is initializing
=> use message to save core state

cypress/integration/DoenetML/tagSpecific/mathinput.spec.js, src/Core/Core.js, src/Core/components/Document.js, src/Core/components/MathInput.js, src/Core/components/Solution.js, src/Core/components/abstract/SectioningComponent.js, src/Viewer/DoenetViewer.jsx, src/Viewer/renderers/answer.jsx, src/Viewer/renderers/booleanInput.jsx, src/Viewer/renderers/choiceInput.jsx, src/Viewer/renderers/mathInput.jsx, src/Viewer/renderers/point.jsx, src/Viewer/renderers/textInput.jsx, src/Viewer/renderers/useDoenetRenderer.jsx, src/Viewer/renderers/vector.jsx
additional robustness to core and doenet viewer messaging
pass messages to record solution view
=> additional message

src/Tools/_framework/Menus/ClassTimes.jsx, src/Tools/uiDocs/uiDocs.jsx, src/_reactComponents/PanelHeaderComponents/DateTime.css, src/_reactComponents/PanelHeaderComponents/DateTime.jsx, src/_reactComponents/PanelHeaderComponents/DropdownMenu.jsx
- Restyled the class times menu
- Created a width prop for DatePicker
- Replaced the button text with icons
- Fixed margins on components
=> Class times menu

src/Tools/_framework/Menus/VersionHistory.jsx, src/Tools/temp/index.jsx, src/Tools/uiDocs/uiDocs.jsx, src/_reactComponents/PanelHeaderComponents/RelatedItems.jsx
Currently being used in Version History
=> Related items component

src/Api/createCourseItem.php
=> Fix sortOrder

src/Tools/cypressTest/index.html, src/Tools/test/index.html
Added CSS variable support for temp, so components using CSS variables will render
=> Test Page - styling bug fix

src/Tools/_framework/Menus/SelectedActivity.jsx
Removing this until it can be fully tested to remove the skipped text bug
=> remove debounce 

src/Tools/_framework/CodeMirror.jsx, src/Viewer/PageViewer.jsx
=> 50% padding on EditorViewer

cypress/integration/DoenetML/tagSpecific/answer.spec.js, cypress/integration/DoenetML/tagSpecific/feedback.spec.js, cypress/integration/DoenetML/tagSpecific/periodicset.spec.js, src/Viewer/renderers/answer.jsx, src/Viewer/renderers/mathInput.jsx
Fixes #1213 
Fixes #1215 
Fixes #1279
=> bug fix: create styled-components outside renderer itself

cypress/integration/DoenetML/tagSpecific/graph.spec.js, src/Core/Dependencies.js, src/Core/components/Graph.js, src/Viewer/renderers/graph.jsx
identicalAxisScales determines aspect ratio if not defined
Resolves #1354
=> graph based on aspect ratio rather than height

src/Api/getCidForAssignment.php, src/Tools/_framework/ToolPanels/AssignmentViewer.jsx, src/Tools/_framework/ToolPanels/DraftAssignmentViewer.jsx, src/Tools/_framework/ToolPanels/EditorViewer.jsx, src/Tools/_framework/ToolPanels/GuestEditorViewer.jsx, src/Tools/_framework/ToolPanels/PublicActivityViewer.jsx
=> Use activity or page label for html title

cypress/integration/DoenetML/tagSpecific/module.spec.js, cypress/integration/DoenetML/tagSpecific/slider.spec.js, src/Media/bafkreicbv4iendtnb6tp5a7t4uhxqlanctippidm3hx3oe5c5din5qqflq.doenet, src/Viewer/renderers/slider.jsx
=> can drag slider even when mouse leaves container

src/Tools/_framework/Footers/MathInputKeyboard.jsx
=> added infinity to keyboard, reorganized Greek

src/Viewer/renderers/graph.jsx, src/Viewer/renderers/sideBySide.jsx, src/Viewer/renderers/tabular.jsx
=> Graph tag positioning

src/Core/components/Graph.js, src/Viewer/renderers/graph.jsx, src/Viewer/renderers/point.jsx
=> graph labels can be added dynamically

cypress/e2e/ActivityViewer/relationshipsAmongPages.cy.js, cypress/e2e/AssignedActivity/multipageActivities.cy.js, cypress/e2e/AssignedActivity/singlepageActivities.cy.js, cypress/e2e/DoenetML/tagSpecific/mathdisplay.cy.js, cypress/e2e/DoenetML/tagSpecific/paginator.cy.js, cypress/e2e/DoenetML/tagSpecific/point.cy.js, cypress/e2e/DoenetML/tagSpecific/sectioning.cy.js, src/Core/Dependencies.js, src/Core/components/Copy.js, src/Core/components/Sectioning.js, src/Core/components/abstract/SectioningComponent.js, src/Core/utils/label.js, src/Viewer/renderers/angle.jsx, src/Viewer/renderers/circle.jsx, src/Viewer/renderers/cobwebPolyline.jsx, src/Viewer/renderers/curve.jsx, src/Viewer/renderers/line.jsx, src/Viewer/renderers/lineSegment.jsx, src/Viewer/renderers/point.jsx, src/Viewer/renderers/polygon.jsx, src/Viewer/renderers/polyline.jsx, src/Viewer/renderers/ray.jsx, src/Viewer/renderers/regionBetweenCurveXAxis.jsx, src/Viewer/renderers/vector.jsx
non-latex labels in graph escape underscore and caret
=> no auto naming in section titles by default

src/Tools/_framework/ToolPanels/GradebookStudentAssignment.jsx, src/Viewer/ActivityViewer.jsx, src/Viewer/PageViewer.jsx
=> create snapshot mode of PageViewer for gradebook

src/Tools/_framework/NewToolRoot.jsx, src/Tools/_framework/ToolPanels/Gradebook.jsx, src/Tools/_framework/ToolPanels/GradebookStudent.jsx
=> small gradebook fixes

cypress/e2e/Gradebook/Gradebook.cy.js, cypress/support/commands.js, cypress_php/api/cypressCreateMultipageActivity.php, src/Api/getGradebookAssignmentAttempts.php, src/Api/loadActivityState.php, src/_reactComponents/Activity/SettingComponents.jsx
=> gradebook loads correct variant index, activity state

cypress/e2e/DoenetML/tagSpecific/math.cy.js, package.json
=> upgrade math-expressions

cypress/e2e/DoenetML/tagSpecific/math.cy.js, cypress/e2e/DoenetML/tagSpecific/mathlist.cy.js, cypress/e2e/DoenetML/tagSpecific/matrix.cy.js, src/Core/ComponentTypes.js, src/Core/Core.js, src/Core/components/Aliases.js, src/Core/components/Math.js, src/Core/components/MathList.js, src/Core/components/Matrix.js, src/Core/components/abstract/BaseComponent.js
invert mathlist with mergeMathLists set
=> matrix component

src/Api/loadTODO.php
=> fixed content by week ignoring unassigned bug

cypress/e2e/DoenetML/tagSpecific/answer.cy.js, cypress/e2e/DoenetML/tagSpecific/codeeditor.cy.js, cypress/e2e/DoenetML/tagSpecific/feedback.cy.js, cypress/e2e/DoenetML/tagSpecific/math.cy.js, cypress/e2e/Events/videoEvents.cy.js, src/Core/Core.js, src/Viewer/renderers/textInput.jsx
=> simplifying performs scalar multiplication with matrix/vector

src/Api/loadAssignments.php, src/Api/loadGradebookAssignmentAttempts.php, src/Api/loadGradebookAssignments.php, src/Api/loadGradebookOverview.php, src/Tools/_framework/ToolPanels/Gradebook.jsx
=> Gradebook respects unassigned

cypress.config.js, cypress/e2e/AssignedActivity/activitySettings.cy.js, cypress/e2e/AssignedActivity/activitySettingsFromDb.cy.js, cypress/support/commands.js, cypress_php/api/cypressUpdateActivitySettings.php, package.json, src/Tools/_framework/Panels/NewMenuPanel.jsx, src/_reactComponents/Activity/SettingComponents.jsx, src/_reactComponents/PanelHeaderComponents/DropdownMenu.jsx, src/_reactComponents/PanelHeaderComponents/IncrementMenu.jsx
1. Setup for dbQuery to reflect changes on DB (cy.task, expect)
2. Tests on activity settings and check for changes in db
=> Cypress activity settings

src/_reactComponents/Activity/SettingComponents.jsx
=> Option to have grade category of null

src/Viewer/renderers/codeEditor.jsx, src/Viewer/renderers/codeViewer.jsx, src/Viewer/renderers/feedback.jsx, src/Viewer/renderers/figure.jsx, src/Viewer/renderers/hint.jsx, src/Viewer/renderers/image.jsx, src/Viewer/renderers/paginatorControls.jsx, src/Viewer/renderers/ref.jsx, src/Viewer/renderers/solution.jsx
This reverts commit bdeb3f7bc3496a047e328a2364f4ff33c6f41259.
=> Revert "Focus highlighting on doenet ml tags (#1660)"

package-lock.json, src/Tools/_framework/NewToolRoot.jsx
Put donut loading animation in an SVG viewBox to account for different screen sizes.
=> Loading animation

cypress/e2e/People/people.cy.js, cypress/fixtures/peopleExample.csv, cypress/fixtures/updatedPeopleExample.csv, cypress/support/commands.js, cypress_php/api/cypressClearCoursePeople.php, package.json, src/Api/mergePeopleData.php, src/Tools/_framework/Menus/LoadPeople.jsx, src/Tools/_framework/ToolPanels/People.jsx, src/_reactComponents/Course/SettingComponents.jsx
1. Add people manually
2. Add/Update people via CSV file merge
3. Withdraw/Enroll people
=> Cypress people test

cypress/e2e/DoenetML/tagSpecific/answer.cy.js, cypress/e2e/DoenetML/tagSpecific/copy.cy.js, cypress/e2e/DoenetML/tagSpecific/math.cy.js, cypress/e2e/DoenetML/tagSpecific/mathinput.cy.js, cypress/e2e/DoenetML/tagSpecific/matrixinput.cy.js, package.json, src/Core/components/Answer.js, src/Core/components/Award.js, src/Core/components/Copy.js, src/Core/components/Math.js, src/Core/components/MathInput.js, src/Core/components/MatrixInput.js, src/Core/components/Number.js, src/Core/utils/booleanLogic.js, src/Core/utils/math.js, src/Core/utils/serializedStateProcessing.js
allow plainCopy even with createComponentOfType
=> parseScientificNotation attribute

package-lock.json, src/Tools/_framework/ToolPanels/HomePanel.jsx
=> Home Page Update

cypress/e2e/DoenetML/tagSpecific/boolean.cy.js, cypress/e2e/DoenetML/tagSpecific/choiceinput.cy.js, cypress/e2e/DoenetML/tagSpecific/math.cy.js, cypress/e2e/DoenetML/tagSpecific/spreadsheet.cy.js, cypress/e2e/Events/videoEvents.cy.js, package.json, src/Core/components/Answer.js
=> fix equality involving symbolic functions

src/Viewer/renderers/answer.jsx, src/Viewer/renderers/booleanInput.css, src/Viewer/renderers/booleanInput.jsx, src/Viewer/renderers/choiceInput.css, src/Viewer/renderers/choiceInput.jsx, src/Viewer/renderers/mathInput.jsx, src/Viewer/renderers/matrixInput.jsx, src/Viewer/renderers/textInput.jsx
=> Initial spacing fixes for input tags

src/Tools/_framework/Footers/MathInputKeyboard.jsx
=> Fix math keyboard square key

cypress/e2e/DoenetML/tagSpecific/image.cy.js, cypress/e2e/DoenetML/tagSpecific/label.cy.js, cypress/e2e/DoenetML/tagSpecific/math.cy.js, cypress/e2e/DoenetML/tagSpecific/mathdisplay.cy.js, cypress/e2e/DoenetML/tagSpecific/text.cy.js, src/Core/Core.js, src/Core/components/Graph.js, src/Core/components/Image.js, src/Core/components/Label.js, src/Core/components/MMeMen.js, src/Core/components/Math.js, src/Core/components/MdMdnMrow.js, src/Core/components/Text.js, src/Core/utils/serializedStateProcessing.js, src/Core/utils/size.js, src/Viewer/renderers/image.jsx, src/Viewer/renderers/label.jsx, src/Viewer/renderers/math.jsx, src/Viewer/renderers/text.jsx
=> text, image, and math in a graph

src/Api/loadGradebookAssignments.php, src/Tools/_framework/ToolPanels/Gradebook.jsx, src/Tools/_framework/ToolPanels/GradebookStudent.jsx
=> Sort gradebook entries by sortOrder

src/Tools/_framework/Menus/GradeDownload.jsx, src/Tools/_framework/ToolPanels/Gradebook.jsx, src/Tools/_framework/ToolPanels/GradebookStudent.jsx
=> Cap for Gradebook points per category 

src/Viewer/renderers/mathInput.jsx, src/Viewer/renderers/textInput.jsx
=> Fixes to mathInput and textInput disabled attribute

src/Viewer/renderers/point.jsx
=> Cross/plus marker styling (for graph points)

src/Api/loadCoursePeople.php, src/Tools/_framework/Menus/GradeDownload.jsx, src/_reactComponents/Course/CourseActions.jsx
=> Enable gradebook download

src/Tools/_framework/Menus/GradeDownload.jsx
=> protect against undefined categories

.devcontainer/devcontainer.json
change the base user to root to support linux. Not a valid solution on non-dev containers
=> update dev container

cypress/e2e/DoenetML/tagSpecific/answer.cy.js, src/Core/components/Answer.js
=> formula can be an answer response

src/Viewer/renderers/slider.jsx
=> Fix: slider and label color in dark mode

src/Core/components/Lists.js, src/Viewer/renderers/list.jsx
=> nested list items switch numbering scheme

cypress/e2e/DoenetML/tagSpecific/graph.cy.js, src/Core/ComponentTypes.js, src/Core/components/Pegboard.js, src/Viewer/renderers/pegboard.jsx
=> pegboard for graph

cypress/e2e/DoenetML/tagSpecific/answer.cy.js, src/Core/components/Answer.js, src/Core/components/TextInput.js, src/Viewer/renderers/textInput.jsx
=> Addeed expanded attribute to answer

cypress/e2e/DoenetML/tagSpecific/mathinput.cy.js, cypress/e2e/DoenetML/tagSpecific/matrixinput.cy.js, src/Core/components/MathInput.js, src/Core/components/MatrixInput.js, src/Viewer/renderers/mathInput.jsx
=> minWidth/minComponentWidth for mathinput/matrixinput

cypress/e2e/DoenetML/tagSpecific/math.cy.js, cypress/e2e/DoenetML/tagSpecific/text.cy.js, cypress/e2e/DoenetML/tagSpecific/textinput.cy.js, src/Core/components/AsList.js, src/Core/components/Function.js, src/Core/components/Label.js, src/Core/components/Latex.js, src/Core/components/Line.js, src/Core/components/MMeMen.js, src/Core/components/Math.js, src/Core/components/MathInput.js, src/Core/components/MathList.js, src/Core/components/MdMdnMrow.js, src/Core/components/Number.js, src/Core/components/PiecewiseFunction.js, src/Core/components/Point.js, src/Core/components/Text.js, src/Core/components/Vector.js, src/Core/components/chemistry/Atom.js, src/Core/components/chemistry/Ion.js, src/Core/components/chemistry/IonicCompound.js, src/Core/components/dynamicalSystems/ODESystem.js, src/Core/utils/math.js
=> text adapts to math or number

src/_reactComponents/Course/CourseNavigator.jsx, src/_reactComponents/Drive/Collection.jsx
=> twirl shows in dark mode

src/Viewer/renderers/feedback.jsx, src/Viewer/renderers/hint.jsx, src/Viewer/renderers/solution.jsx
=> fix dark mode styling for feedback, hint, solution

index.html, src/Tools/cypressTest/index.html, src/Tools/test/index.html, src/Viewer/PageViewer.jsx, src/Viewer/renderers/booleanInput.css, src/Viewer/renderers/section.jsx
=> override Chakra styling changes in DoenetML

cypress/e2e/DoenetML/tagSpecific/animatefromsequence.cy.js, src/Core/utils/math.js
=> Numbers adapted to maths have more robust inverse

src/Viewer/PageViewer.jsx
=> if have error in saved render state, fall back to state from core

src/Viewer/renderers/booleanInput.css, src/Viewer/renderers/booleanInput.jsx, src/Viewer/renderers/choiceInput.css, src/Viewer/renderers/choiceInput.jsx
=> Style disabled checkboxes and radio buttons

index.html, src/Core/components/SideBySide.js, src/Tools/_framework/Paths/Home.jsx, src/Viewer/PageViewer.jsx
=> override Chakra styling changes in DoenetML lists

public/api/saveDoenetML.php, src/Tools/_framework/ToolPanels/EditorViewer.jsx, src/Tools/_framework/ToolPanels/GuestEditorViewer.jsx, src/_sharedRecoil/EditorViewerRecoil.jsx, src/_utils/hooks/useSaveDraft.jsx
- either as separate users or separate tabs
- Uses optimistic concurrency control
=> Avoid clobbering editor updates when 2 instances of the editor are open

cypress.config.js, cypress/e2e/DoenetML/tagSpecific/codeeditor.cy.js, src/Tools/_framework/CodeMirror.jsx, src/Tools/_framework/ToolPanels/DoenetMLEditor.jsx, src/Tools/_framework/ToolPanels/GuestDoenetMLEditor.jsx, src/Viewer/PageViewer.jsx, src/Viewer/renderers/codeEditor.jsx, src/Viewer/renderers/codeViewer.jsx
=> DoenetML editor fixes

src/Tools/_framework/Paths/Home.jsx, src/Tools/_framework/Paths/SiteHeader.jsx, src/_reactComponents/PanelHeaderComponents/Carousel.jsx, src/index.jsx
Pending responsiveness on this branch
=> Chakra Revamp + Light Dark mode

cypress/e2e/DoenetML/tagSpecific/circle.cy.js, cypress/e2e/DoenetML/tagSpecific/point2.cy.js, src/Core/Core.js, src/Core/components/Circle.js, src/Core/components/Graph.js, src/Core/components/Point.js, src/Viewer/renderers/circle.jsx, src/Viewer/renderers/point.jsx, src/Viewer/renderers/utils/graph.js, src/Viewer/renderers/utils/offGraphIndicators.js
Given that changes in #2116 allow components to leave graph bounds more easily, provide indicators when this happens.
=> off-graph indicator for points and circles

cypress/e2e/DoenetML/tagSpecific/codeeditor.cy.js, src/Core/Core.js, src/Core/components/CodeEditor.js, src/Core/components/RenderDoenetML.js, src/Viewer/renderers/renderDoenetML.jsx
Allows receovery from errors in DoenetML
=> use a separate core for RenderDoenetML

cypress/e2e/DoenetML/tagSpecific/booleaninput.cy.js, cypress/e2e/DoenetML/tagSpecific/choiceinput.cy.js, cypress/e2e/DoenetML/tagSpecific/codeeditor.cy.js, cypress/e2e/DoenetML/tagSpecific/mathinput.cy.js, cypress/e2e/DoenetML/tagSpecific/matrixinput.cy.js, cypress/e2e/DoenetML/tagSpecific/textinput.cy.js, src/Core/Core.js, src/Core/Dependencies.js, src/Core/components/Angle.js, src/Core/components/BooleanInput.js, src/Core/components/ChoiceInput.js, src/Core/components/CodeEditor.js, src/Core/components/Curve.js, src/Core/components/Function.js, src/Core/components/Line.js, src/Core/components/Math.js, src/Core/components/MathInput.js, src/Core/components/MatrixInput.js, src/Core/components/Number.js, src/Core/components/TextInput.js, src/Core/components/abstract/FunctionBaseOperator.js, src/Core/components/abstract/GraphicalComponent.js, src/Core/utils/label.js, src/Core/utils/serializedStateProcessing.js, src/Core/utils/stateVariables.js, src/Viewer/renderers/choiceInput.jsx, src/Viewer/renderers/mathInput.jsx
=> valueChanged and immediateValueChanged properties

cypress/e2e/DoenetML/baseComponent/doenetMLtext.cy.js, src/Core/Core.js, src/Core/components/CodeEditor.js, src/Core/components/Verbatim.js, src/Media/bafkreievuawsojoy4kzz7sbjvc2sxreqw6bzg3gow2jwor23aknjsmihcy.doenet
=> don't create children of displayDoenetML or codeEditor

src/Core/components/Award.js, src/Viewer/renderers/chart.jsx
removed unused award attribute
=> fix chart renderer bug

cypress/e2e/DoenetML/answerValidation/videoProgress.cy.js, cypress/e2e/DoenetML/dynamicalsystem/odesystem.cy.js, cypress/e2e/DoenetML/tagSpecific/angle.cy.js, cypress/e2e/DoenetML/tagSpecific/copy2.cy.js, cypress/e2e/DoenetML/tagSpecific/curve.bezier.cy.js, cypress/e2e/DoenetML/tagSpecific/evaluate.cy.js, cypress/e2e/DoenetML/tagSpecific/function.cy.js, cypress/e2e/DoenetML/tagSpecific/functionoperators.cy.js, cypress/e2e/DoenetML/tagSpecific/graph.cy.js, cypress/e2e/DoenetML/tagSpecific/line.cy.js, cypress/e2e/DoenetML/tagSpecific/math.cy.js, cypress/e2e/DoenetML/tagSpecific/mathinput.cy.js, cypress/e2e/DoenetML/tagSpecific/mathlist.cy.js, cypress/e2e/DoenetML/tagSpecific/number.cy.js, cypress/e2e/DoenetML/tagSpecific/numberlist.cy.js, cypress/e2e/DoenetML/tagSpecific/point2.cy.js, cypress/e2e/DoenetML/tagSpecific/ray.cy.js, cypress/e2e/DoenetML/tagSpecific/samplerandomnumbers.cy.js, cypress/e2e/DoenetML/tagSpecific/selectfromsequence.cy.js, cypress/e2e/DoenetML/tagSpecific/selectrandomnumbers.cy.js, cypress/e2e/DoenetML/tagSpecific/sequence.cy.js, cypress/e2e/DoenetML/tagSpecific/substitute.cy.js, cypress/e2e/DoenetML/tagSpecific/vector.cy.js, cypress/e2e/DoenetML/tagSpecific/video.cy.js, src/Core/utils/rounding.js, src/Core/utils/serializedStateProcessing.js
math and number lists ignore rounding attributes of children
=> specifying display digits or decimals alone ignores other rounding factor

cypress/e2e/DoenetML/tagSpecific/circle.cy.js, cypress/e2e/DoenetML/tagSpecific/curve.bezier.cy.js, cypress/e2e/DoenetML/tagSpecific/function.cy.js, cypress/e2e/DoenetML/tagSpecific/line.cy.js, cypress/e2e/DoenetML/tagSpecific/linesegment.cy.js, cypress/e2e/DoenetML/tagSpecific/polygon.cy.js, cypress/e2e/DoenetML/tagSpecific/polyline.cy.js, cypress/e2e/DoenetML/tagSpecific/ray.cy.js, cypress/e2e/DoenetML/tagSpecific/vector.cy.js, src/Core/components/Curve.js, src/Core/components/Function.js, src/Core/components/LineSegment.js, src/Core/components/Polyline.js, src/Viewer/renderers/ray.jsx
=> graphical components handle more bad attributes

src/Core/components/Angle.js, src/Core/components/Curve.js, src/Core/components/Polyline.js, src/Core/components/Vector.js, src/Core/utils/serializedStateProcessing.js, src/Viewer/renderers/angle.jsx, src/Viewer/renderers/curve.jsx, src/Viewer/renderers/lineSegment.jsx, src/Viewer/renderers/polygon.jsx, src/Viewer/renderers/polyline.jsx, src/Viewer/renderers/vector.jsx
=> showCoordsWhenDragging for components with built-in points

cypress/e2e/DoenetML/tagSpecific/functionoperators.cy.js, src/Core/components/FunctionOperators.js, src/Core/components/abstract/FunctionBaseOperator.js
=> derivative of vector-valued functions

cypress/e2e/DoenetML/tagSpecific/samplerandomnumbers.cy.js, src/Core/components/SampleRandomNumbers.js, src/Core/utils/randomNumbers.js
=> exclude values for sampling discrete uniform random numbers

cypress/e2e/DoenetML/tagSpecific/curve.parametrized.cy.js, src/Core/components/Curve.js, src/Core/components/Function.js
=> Parametrized curve from vector-valued function

src/Viewer/renderers/paginatorControls.jsx
=> use Button component for paginator controls renderer

cypress/e2e/DoenetML/tagSpecific/matrix.cy.js, src/Core/components/Math.js, src/Core/components/Matrix.js, src/Core/components/MatrixInput.js
=> create matrix from string/math children

cypress/e2e/DoenetML/tagSpecific/point2.cy.js, src/Viewer/renderers/point.jsx, src/Viewer/renderers/utils/offGraphIndicators.js
=> handle complex point values in graph

cypress/e2e/DoenetML/tagSpecific/updatevalue.cy.js, src/Core/Core.js
=> trigger with source name on unnamed copies

cypress/e2e/DoenetML/tagSpecific/mathlist.cy.js, package.json, src/Core/components/Math.js, src/Core/components/MathList.js
=> maxNumber works correctly for mathList with mergeMathLists

cypress/e2e/DoenetML/tagSpecific/codeeditor.cy.js, src/Core/components/CodeEditor.js, src/Core/components/CodeViewer.js, src/Viewer/renderers/codeEditor.jsx
=> viewerRatio works for side-by-side editor/viewer

cypress/e2e/Portfolio/ShareActivities.cy.js, cypress/support/commands.js, cypress_php/api/cypressAutoSignin.php, src/Viewer/PageViewer.jsx, src/Viewer/renderers/ref.jsx
=> doenetId refs in portfolio link to portfolio viewer

cypress/e2e/DoenetML/tagSpecific/ref.cy.js, src/Core/Core.js, src/Core/CoreWorker.js, src/Viewer/PageViewer.jsx
=> ref into descendant of aside opens aside

cypress/e2e/DoenetML/tagSpecific/animatefromsequence.cy.js, cypress/e2e/DoenetML/tagSpecific/copy2.cy.js, cypress/e2e/DoenetML/tagSpecific/updatevalue.cy.js, src/Core/Dependencies.js, src/Core/components/AnimateFromSequence.js, src/Core/components/CodeEditor.js, src/Core/components/Copy.js, src/Core/components/UpdateValue.js, src/Core/components/Video.js, src/Core/utils/label.js, src/Core/utils/serializedStateProcessing.js, src/Viewer/renderers/label.jsx
=> dontRecurseToShadows replaces shadowDepth in dependencies

cypress/e2e/DoenetML/tagSpecific/mathlist.cy.js, cypress/e2e/DoenetML/tagSpecific/matrix.cy.js, cypress/e2e/DoenetML/tagSpecific/matrixinput.cy.js, src/Core/components/Column.js, src/Core/components/Math.js, src/Core/components/MathList.js, src/Core/components/Matrix.js, src/Core/components/MatrixInput.js, src/Core/components/Row.js
=> matrix fixes

src/Viewer/renderers/orbitalDiagramInput.jsx
=> Use custom buttons in orbitalDiagramInput

cypress/e2e/Portfolio/PortfolioVariants.cy.js, cypress/e2e/Portfolio/ShareActivities.cy.js, src/Tools/_framework/ChakraBasedComponents/VariantSelect.jsx, src/Tools/_framework/Paths/PortfolioActivityEditor.jsx, src/Tools/_framework/Paths/PortfolioActivityViewer.jsx, src/Tools/_framework/Paths/PublicEditor.jsx
=> Portfolio Variant Selectors

cypress/e2e/DoenetML/errorsAndWarnings/errors.cy.js, src/Parser/parser.js
=> Cannot create abstract components with DoenetML

cypress/e2e/DoenetML/tagSpecific/evaluate.cy.js, cypress/e2e/DoenetML/tagSpecific/function.cy.js, src/Core/Core.js, src/Core/components/Function.js, src/Core/components/FunctionIterates.js, src/Core/utils/domain.js, src/Core/utils/function.js, src/Core/utils/serializedStateProcessing.js
customized warning for invalid children in attributes
Fixes #2158.
=> domain of function is a public state variable

cypress/e2e/DoenetML/tagSpecific/circle.cy.js, cypress/e2e/DoenetML/tagSpecific/polygon.cy.js, cypress/e2e/DoenetML/tagSpecific/polyline.cy.js, cypress/e2e/DoenetML/tagSpecific/rectangle.cy.js, cypress/e2e/DoenetML/tagSpecific/triangle.cy.js, src/Core/components/Circle.js, src/Core/components/Polygon.js, src/Core/components/Polyline.js
length of polyline
area and circumference of circle
Fixes: #2301
=> area and perimeter of polygon

cypress/e2e/AssignedActivity/multipageActivities.cy.js, cypress/e2e/DoenetML/errorsAndWarnings/warnings.cy.js, src/Core/Core.js, src/Tools/_framework/ToolPanels/AssignmentViewer.jsx, src/Tools/_framework/ToolPanels/EndExamPanel.jsx, src/Tools/_framework/ToolPanels/GradebookStudentAssignment.jsx, src/Viewer/ActivityViewer.jsx
=> load page doenetML if loading old saved state

src/Tools/_framework/Menus/SupportingFilesMenu.jsx, src/Tools/_framework/Paths/CourseActivityEditor.jsx, src/Tools/_framework/Paths/PortfolioActivityEditor.jsx
=> no height in image support files

public/api/baseModel.php, public/api/updateAssignmentSettingsByKey.php, public/api/updateContentSettingsByKey.php
- these utility functions will log errors and return error IDs to clients that they can share with us for finding the specific logs relating to their issue
=> Adding debug logging and utility functions for mysql queries

src/_reactComponents/Course/CourseActions.jsx
Fixes issues with disappearing course items in the course navigation tree.
=> Be more permissive of different orderings of course items from the back-end

cypress/e2e/DoenetML/tagSpecific/functionoperators.cy.js, src/Core/utils/function.js
Backport of Doenet/DoenetML#148
=> fix bug in derivative of invalid interpolated function

src/Tools/_framework/Paths/Home.jsx, src/Tools/_framework/Paths/HomeIntroVideo.jsx
- fonts were getting too small
- content was overflowing viewport and leaving horizontal scroll space
=> Fix various style problems on homepage on mobile

client/src/Tools/_framework/Paths/ActivityEditor.jsx, client/src/Tools/_framework/Paths/ActivityViewer.jsx, client/src/Tools/_framework/Paths/AssignmentViewer.jsx, client/src/Tools/_framework/ToolPanels/AssignmentPreview.jsx
This PR updates the styling of the activity viewer so that the large header scrolls off the screen
=> Update activity viewer styling

server/src/model.test.ts, server/src/model.ts
This PR modifies the getAllAssignmentScores function to recurse to all subfolders.
=> Get assignment scores with folders

server/src/index.ts, server/src/model.test.ts, server/src/model.ts
The assignment score apis `getAllAssignmentScores` and `getStudentData` now perform a depth-first search of all subfolders to produce an ordered list of all activities that are in a folder and its subfolders.
=> assignment score apis return ordered activity list

client/src/Tools/_framework/Paths/Admin.jsx, client/src/Tools/_framework/Paths/Library.jsx, client/src/Tools/_framework/Paths/SiteHeader.jsx
Changes:
- Nav bar page tabs collapse into hamburger dropdown when screen is small
- Email, discord, and documentation buttons now found under "Help" dropdown
=> Mobile-friendly navbar layout

client/src/Tools/_framework/Paths/AllAssignmentScores.tsx, client/src/Tools/_framework/Paths/AssignmentViewer.jsx, server/src/model.test.ts, server/src/model.ts
Some small changes so that /classCode/:code path works again. Both viewing activity and saving scores to database work.
=> Fix assign activity using code

client/src/Tools/_framework/Paths/AllAssignmentScores.tsx, client/src/Tools/_framework/Paths/AssignmentStudentData.jsx, client/src/Tools/_framework/Paths/StudentData.tsx, client/src/index.jsx
Update the various score views to work with the API change
=> Fix score views to match with API again

client/src/Tools/_framework/Paths/Activities.jsx, client/src/Tools/_framework/Paths/ActivityEditor.jsx, client/src/Tools/_framework/Paths/Admin.jsx, client/src/Tools/_framework/Paths/Assignments.jsx, client/src/Tools/_framework/Paths/Community.jsx, client/src/Tools/_framework/Paths/PublicPortfolio.jsx, client/src/_reactComponents/PanelHeaderComponents/Carousel.jsx, client/src/_reactComponents/PanelHeaderComponents/ContentCard.jsx, server/src/index.ts, server/src/model.ts
This PR adds additional features for manipulating activities with the new folder system:
- duplicating activities
- renaming activities and folders
- changing folder and activities names directly on the card
=> Frontend folders

client/src/Tools/_framework/Paths/Activities.jsx, client/src/Tools/_framework/Paths/Assigned.jsx, client/src/Tools/_framework/Paths/AssignmentData.jsx, client/src/Tools/_framework/Paths/AssignmentStudentData.jsx, client/src/Tools/_framework/Paths/SiteHeader.jsx, client/src/Tools/_framework/Paths/StudentData.tsx, client/src/_reactComponents/PanelHeaderComponents/ContentCard.jsx, client/src/index.jsx, server/src/index.ts, server/src/model.test.ts, server/src/model.ts
This PR adds an "Assigned" tab which shows the activities that are assigned to a given user, which currently means that user has asssignment score data entered. The user can access the assigments and also access their score data.
=> Add Assigned tab

client/src/Tools/_framework/Paths/Activities.jsx, server/src/index.ts
This PR adds "Move left" and "Move right" menu options on content cards to move them within their folder.
=> ability to move content left and right within a folder

client/src/Tools/_framework/Paths/Community.jsx, server/prisma/migrations/20240708144124_sort_index_promoted/migration.sql, server/prisma/schema.prisma, server/prisma/seed.ts, server/src/index.ts, server/src/model.test.ts, server/src/model.ts
This PR adds the ability for an admin to move promoted content and promoted content groups.
=> move promoted content and promoted content groups

client/src/Tools/_framework/Paths/Activities.jsx, server/src/model.ts
This PR fixes a bug where moving content placed it in the root folder
=> bugfix: correctly move content within folder

client/src/Tools/_framework/Paths/Activities.jsx, client/src/Tools/_framework/Paths/ActivityEditor.jsx, client/src/Tools/_framework/Paths/ActivityViewer.jsx, client/src/Tools/_framework/Paths/AllAssignmentScores.tsx, client/src/Tools/_framework/Paths/Assigned.jsx, client/src/Tools/_framework/Paths/AssignmentAnswerResponseHistory.jsx, client/src/Tools/_framework/Paths/AssignmentAnswerResponses.jsx, client/src/Tools/_framework/Paths/AssignmentData.jsx, client/src/Tools/_framework/Paths/AssignmentStudentData.jsx, client/src/Tools/_framework/Paths/Community.jsx, client/src/Tools/_framework/Paths/PublicActivities.jsx, client/src/Tools/_framework/Paths/PublicEditor.jsx, client/src/_reactComponents/PanelHeaderComponents/Carousel.jsx, client/src/_reactComponents/PanelHeaderComponents/ContentCard.jsx, client/src/index.jsx, server/src/index.ts, server/src/model.test.ts, server/src/model.ts
This PR add the ability to search public folders as well as activities and navigate among public folders. It also restores the ability to search for authors who have public content.
=> Search and navigate public folders

client/src/Tools/_framework/Paths/Activities.tsx, client/src/Tools/_framework/Paths/ActivityViewer.tsx, client/src/Tools/_framework/Paths/PublicActivities.tsx, server/src/index.ts, server/src/model.test.ts, server/src/model.ts
This PR adds the ability to search one's own activities, either at the base level or within a given folder.
=> Search my activities

client/package-lock.json, client/package.json, client/src/Tools/_framework/Paths/Activities.tsx, client/src/Tools/_framework/Paths/ActivityEditor.tsx, client/src/Tools/_framework/ToolPanels/AssignActivityControls.tsx, client/src/Tools/_framework/ToolPanels/AssignmentSettingsDrawer.tsx, client/src/Tools/_framework/ToolPanels/GeneralContentControls.tsx, package-lock.json, server/package-lock.json, server/package.json
- allow custom close times in initial quick assign
- separate assignment and content settings drawers
=> Improvements for assigning activities

client/src/Tools/_framework/Paths/Activities.tsx, client/src/Tools/_framework/ToolPanels/MoveContentToFolder.tsx
- fix regression in MoveContentToFolder
- move search icon to the left
=> fix regression

server/package-lock.json, server/package.json, server/prisma/migrations/20240812145822_full_text_indices/migration.sql, server/prisma/migrations/20240812180723_full_text_search_indices/migration.sql, server/prisma/schema.prisma, server/src/index.ts, server/src/model.test.ts, server/src/model.ts
Add full text search to community search and my folder search. Search activity content, activity name, content classifications, and (for community search only) owner names.
=> Full text search

server/package-lock.json, server/package.json, server/prisma/schema.prisma, server/src/index.ts, server/src/model.test.ts, server/src/model.ts, server/src/types.ts, server/src/utils/binary-uuid.ts, server/src/utils/uuid.ts
This PR upgrades to prisma version 6.
The main adjustment needed was to change the `Buffer` of our UUIDs to `Uint8Array`.
=> upgrade to prisma 6

client/cypress/e2e/SettingsPanel/classifications.cy.ts, client/src/Tools/_framework/ToolPanels/ClassificationSettings.tsx, client/src/Tools/_framework/ToolPanels/ContentSettingsDrawer.tsx, client/src/_utils/types.ts, server/prisma/migrations/20241210052315_classification_subcategory/migration.sql, server/prisma/schema.prisma, server/prisma/seed-data/common-core-math.json, server/prisma/seed-data/mn-math.json, server/prisma/seed.ts, server/src/index.ts, server/src/model.test.ts, server/src/model.ts, server/src/types.ts, server/tsconfig.json
This PR revises the approach for adding classifications of activities. Category searching and browsing are combined into a single search function that uses full text searching. The classification controls are expanded into a two-panel format.
=> revise add classifications approach

server/prisma/seed/hscmath-additions.json, server/prisma/seed/seed-classifications.ts
This PR adds a few classifications to the High school and college math system that aren't in the WeBWorK taxonomy.
=> add classifications to HS/C Math not in WeBWorK

client/src/Tools/_framework/Paths/Explore.tsx, client/src/Widgets/Card.tsx, server/prisma/migrations/20250115153814_content_views/migration.sql, server/prisma/schema.prisma, server/src/index.ts, server/src/model.ts, server/src/test/assign.test.ts, server/src/test/search.test.ts
This PR adds  adds the ability to view content ordered by number of recent views, i.e., a view of "trending" content. To illustrate this possibility, the Explore tab has a separate "Trending" section when browsing content.
=> Explore trending content based on recent views

client/src/Tools/_framework/ToolPanels/AssignmentSettings.tsx, client/src/Tools/_framework/ToolPanels/ContentSettingsDrawer.tsx, client/src/Tools/_framework/ToolPanels/GeneralContentControls.tsx, client/src/Tools/_framework/ToolPanels/ShareDrawer.tsx, client/src/Tools/_framework/ToolPanels/ShareSettings.tsx, server/prisma/seed.ts, server/src/index.ts
Update the layout in share settings, show feedback in general content controls, and other small tweaks.
=> Formatting fixes

client/src/Tools/_framework/Paths/Activities.tsx, client/src/Tools/_framework/Paths/Assigned.tsx, client/src/Tools/_framework/Paths/Curation.tsx, client/src/Tools/_framework/Paths/Explore.tsx, client/src/Tools/_framework/Paths/SharedActivities.tsx, client/src/Tools/_framework/Paths/Trash.tsx, client/src/Tools/_framework/ToolPanels/CompoundActivityEditor.tsx, client/src/Tools/_framework/ToolPanels/DeleteModal.tsx, client/src/Widgets/Card.tsx, client/src/Widgets/CardList.tsx, client/src/_utils/assignment.ts, client/src/_utils/dateUtilityFunction.ts, client/src/index.tsx, server/prisma/migrations/20250529162358_undelete/migration.sql, server/prisma/schema.prisma, server/src/query/activity.ts, server/src/query/activity_edit_view.ts, server/src/query/assign.ts, server/src/query/content_list.ts, server/src/query/copy_move.ts, server/src/query/curate.ts, server/src/query/explore.ts, server/src/query/promoted.ts, server/src/query/scores.ts, server/src/query/share.ts, server/src/query/stats.ts, server/src/routes/contentListRoutes.ts, server/src/routes/updateContentRoutes.ts, server/src/test/activity.test.ts, server/src/utils/permissions.ts
Click "See My Trash" on Activities page to view your deleted content from up to 30 days ago. You can restore any of the content in the trash.
Notes
- Fixes #2564
- Backend uses `isDeletedOn` and `deletionRootId` instead of `isDeleted`
- The migration is edited to not lose any data. Tested on my local environment.
=> Add page to restore deleted content

client/.prettierignore, client/cypress/e2e/Events/videoEvents.cy.ts, client/src/drawerTabs/GeneralContentControls.tsx, client/src/index.tsx
Renaming content and pressing enter no longer displays an error page. Resolves #2575
Also clean up React Router paths.
=> Fix rename content

client/package-lock.json, client/package.json, client/src/paths/AssignmentViewer.tsx, client/src/paths/Home.tsx, server/prisma/seed.ts, server/src/test/activity.test.ts, server/src/test/assign.test.ts
This PR upgrades the DoenetML version and fixes regressions due to changes in the format of messages.
=> fix regressions with new DoenetML version

client/package-lock.json, client/package.json, client/src/paths/AllAssignmentScores.tsx, client/src/paths/AssignmentResponseOverview.tsx, client/src/utils/scores.ts, server/src/query/assign.ts, server/src/query/scores.ts, server/src/test/assign.test.ts
Add the ability for users to download the scores of their students.
Two buttons: One button on assignment page, another button on folder scores pages.
Changed `getAssignmentResponseOverview` and `getAllAssignmentScores` to hide anonymous user fake emails.
=> Button to download scores as CSV file

client/src/RouterLogo.tsx, client/src/widgets/Card.tsx, client/src/widgets/FilterPanel.tsx
Fix some of the errors and warnings that have been hanging around in the console for a while
* Category icons missing keys
* hasLink property on logo
* FilterPanel accordion over-specified
=> Fix simple React errors and warnings

client/src/paths/Home.tsx
Improve the homepage slightly
* More natural title size
* Fix office hours time
* Events section
* Fix "Learn to Make Your Own" link
=> Better homepage

client/src/paths/AssignmentViewer.tsx, server/src/index.ts, server/src/routes/assignRoutes.ts, server/src/routes/infoRoutes.ts, server/src/routes/loginRoutes.ts
Anonymous login no longer handled by `getAssignmentViewerDataFromCode`. Now it is its own endpoint, `api/login/anonymous`.
=> Separate anonymous login to its own API endpoint

client/src/popups/ShareMyContentModal.tsx
PR #2651 broke sharing with specific users for all activity types. This PR fixes it.
=> Fix sharing with emails
