Doenet/DoenetTools

package-lock.json
package.json

"The FSEvents API in MacOS allows applications to register for notifications of changes to a given directory tree."
This eliminates the high CPU and power usage of an idle Webpack instance started by `npm start`

Eliminates high CPU usage of watching files on Mac

---

package.json

`npm run publish:db` work and is now the preferred export method as it includes the missing create db statements

fix: publish command

---

src/Viewer/renderers/ref.jsx

Fixes #1772
Example code:
``` 
<p>Click 
<ref uri="doenet:doenetId=_DG5JOeFNTc5rpWuf2uA-q" 
createButton="true">here</ref> 
to go back to the index</p>
```

Updated styling for <ref> button

---

cypress/e2e/DoenetML/tagSpecific/angle.cy.js
src/Core/components/Angle.js
src/Viewer/renderers/angle.jsx

EmphasizeRightAngle attribute for angle

---

cypress/e2e/DoenetML/answerValidation/matchpartial.cy.js
cypress/e2e/DoenetML/equality/mathexpressions.cy.js
cypress/e2e/DoenetML/tagSpecific/evaluate.cy.js
cypress/e2e/DoenetML/tagSpecific/function.cy.js
cypress/e2e/DoenetML/tagSpecific/functioniterates.cy.js
cypress/e2e/DoenetML/tagSpecific/math.cy.js
cypress/e2e/DoenetML/tagSpecific/mathoperators.cy.js
cypress/e2e/DoenetML/tagSpecific/matrixinput.cy.js
cypress/e2e/DoenetML/tagSpecific/point.cy.js
cypress/e2e/DoenetML/tagSpecific/ray.cy.js
cypress/e2e/DoenetML/tagSpecific/vector.cy.js
package-lock.json
package.json
src/Core/Core.js
src/Core/components/DiscreteSimulationResultList.js
src/Core/components/DiscreteSimulationResultPolyline.js
src/Core/components/Evaluate.js
src/Core/components/Function.js
src/Core/components/FunctionIterates.js
src/Core/components/Math.js
src/Core/components/MatrixInput.js
src/Core/components/Point.js
src/Core/components/Ray.js
src/Core/components/Spreadsheet.js
src/Core/components/Vector.js
src/Core/utils/booleanLogic.js
src/Core/utils/checkEquality.js
src/Core/utils/function.js
src/Core/utils/math.js
src/Viewer/renderers/mathInput.jsx

This brings in changes from the math expressions library for commits between https://github.com/Doenet/math-expressions/commit/ab71641e5e1171c352af0941eaaf2624cea77216 and https://github.com/Doenet/math-expressions/commit/dd6c3b286cb1f78e897b0b3baa363374913e08d2
Summary of changes in new version of math expressions:
-  enable numerical comparison of vecs                  
-  add line segments
-  set containment with equality
-  begin support for integrals 
-  introduce a few units 
-  angle as operator, normalize arg order when compare 
-  parallel operator 
-  perp operator and lone symbol 
-  altvector with langle/rangle notation 
-  binom, vec, angle, floor, ceil exponents of non trig function are not moved outside
-  latex operatorname, nCr, nPr
-  evaluate log_b(a) 
-  function …

New math features

---

cypress/e2e/DoenetML/dynamicalsystem/odesystem.cy.js
cypress/e2e/DoenetML/tagSpecific/curve.cy.js
cypress/e2e/DoenetML/tagSpecific/function.cy.js
cypress/e2e/DoenetML/tagSpecific/functionoperators.cy.js
src/Core/Core.js
src/Core/components/Curve.js
src/Core/components/Function.js
src/Core/components/abstract/FunctionBaseOperator.js
src/Core/components/dynamicalSystems/ODESystem.js
src/Core/utils/function.js
src/Viewer/renderers/curve.jsx

Expose curve component functions as public state variables

---

cypress/e2e/DoenetML/tagSpecific/answer.cy.js
src/Core/components/Answer.js

handGraded attribute for answer

---

src/Viewer/PageViewer.jsx

Fix: ref mailto v2

---

cypress/e2e/DoenetML/assignNames/collections.cy.js
cypress/e2e/DoenetML/tagSpecific/feedback.cy.js
cypress/e2e/DoenetML/tagSpecific/piecewisefunction.cy.js
src/Core/ComponentTypes.js
src/Core/components/Function.js
src/Core/components/PiecewiseFunction.js
src/Core/utils/function.js

piecewise function

---

public/api/loadPromotedContent.php
public/api/removePromotedContent.php
src/Tools/_framework/Paths/Community.jsx
src/_reactComponents/PanelHeaderComponents/Carousel.jsx

With these changes admins can remove individual materials from promoted groups.
There was a small bug with the charkra pulldown menus not displaying properly within our carousels provided by the Swiper library. We might need to fix that at some point, if we later need a menu on a card in a carousel, but for the sake of getting this done faster, as well as making it easier for admins to see everything that is in a promoted list while they managed it, I just moved the admin view of the community page to show all of the promoted groups as simple lists of cards without carousels.
Regular users still see the carousels to make it easier to view diversity categories featured and not get overloaded looking at too much at once.

Allow removing promoted content

---

cypress/e2e/DoenetML/tagSpecific/codeeditor.cy.js
cypress/e2e/Editor/Editor.cy.js
src/Tools/_framework/CodeMirror.jsx

The API we were listening to does not fire events for undo/redo. This updateListener does give us events for these, although it also gives events for other things like changing cursor position or the selection range with a click and drag. The docs claim computing "docChanged" is cheap, so it doesn't look like doing this should be problematic, but it is definitely unintuitive that undo/redo don't fire events for the other changeFilter API. Several events will fire for both of these handlers, like a regular typing event, but it shouldn't be a problem as the actual save is debounced anyway so we won't get extra events to the server.
Fixes #1315

Fix saving after undo

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.extend.yml
doenet_docker/apache/Dockerfile

This reverts commit 6f8827840661b8d92bb9a6700502cc301ad58819.
This change is breaking several things in local dev environments on mac. The things we identified so far were the inability to run cypress tests against the built site on port 8080 and we also cannot connect to our local mysql databases with various tools (graphical query tool and the mysql cli client)

Revert "Update dev enviroment to support Codespaces (#2172)"

---

cypress/e2e/DoenetML/tagSpecific/codeeditor.cy.js
src/Core/components/CodeEditor.js
src/Core/utils/variants.js

ignore variants from children of <codeEditor>

---

cypress/e2e/Navigation/Activity.cy.js
package.json
src/_reactComponents/Course/CourseActions.jsx

Fix bugs around adding objects below a section that contains an activity as the last child below it.
I still want to add some more tests for having the different types of objects selected. There is also an opportunity to consolidate some of this repeated code that I'm trying to figure out the right way to restructure.

Allow adding two activities to a section, and fix page crashing unhappy donut messages when adding collections or sub-sections

---

package-lock.json
package.json

Chakra was causing a failure on old (pre-Mojave) macOS systems due to the use of `Array.prototype.at()`

update chakra dependency

---

cypress/e2e/AlertQueue/assignmentAlertQueue.cy.js
public/api/baseModel.php
public/api/getQuickCheckSignedIn.php
public/api/recordEvent.php
public/api/saveActivityState.php
public/api/saveCreditForItem.php
public/api/savePageState.php
src/Core/Core.js
src/Tools/_framework/ToolPanels/AssignmentViewer.jsx

Used `Base_Model` to plug in logging for the touched php files. Each one has guards for http response codes in core – where they are exclusively called from. Also fixes an issue with `getQuickCheckSignedIn` polluting the error log

Add logging to php files related to exam data

---

src/Tools/_framework/Paths/Home.jsx

- make the doenet logo the anchor we jump to, so it doesn't end up cut off after the browser navigation from a click on the link in the top bar

Small fixes, give the portfolio viewer link to the animation tutorial

---

src/Tools/_framework/Paths/HomeIntroVideo.jsx

- this is unintinutive, but the video for the planets orbiting is not a square it has black bars on the margins, because I did some light editing in a video editor and it just exported it in a standard 9:16 aspect ratio
- I decided to just fix how I wanted it displayed using CSS, but the recent changes accidentally put this text in the invisible overlapping space where I'm hiding the margin of the video, this just moves it outside of that inner div to the outer container

Small CSS fix - restore link to the planet animation tutorial

---

server/src/index.ts
server/src/model.test.ts
server/src/model.ts

The `deleteFolder` function now correctly recurses to all its subfolders, deleting the folders, activities, and documents contained in them.
The `getFolderContent` function now supercedes and replaces the `listUserContent` function.

deleteFolder recurses to subfolders

---

server/src/index.ts
server/src/model.test.ts
server/src/model.ts

Since sortIndex is a `bigint`, it doesn't directly serialize and throw an expection if sent raw in the server response. This PR makes sure that no apis send `sortIndex`. It also does other small cleanup on the server code.

make sure sortIndex is not sent as response

---

client/src/Tools/_framework/Paths/ActivityViewer.tsx
client/src/Tools/_framework/Paths/PublicEditor.tsx
client/src/Tools/_framework/ToolPanels/CopyActivityAndReportFinish.tsx
client/src/index.jsx
server/src/index.ts
server/src/model.ts

Improve the behavior of the `Copy to Activities` button in the activity viewer and the public editor.
When a user clicks the `Copy to Activities` button, a dialog opens indicating that the copy is occurring. When the copy is finished, the dialog gives the option for the user to go to their Activities.

Improve Copy to Activities

---

client/src/Tools/_framework/ToolPanels/ClassificationSettings.tsx
client/src/_utils/types.ts
server/prisma/migrations/20241217224818_non_tree_classifications/migration.sql
server/prisma/schema.prisma
server/prisma/seed-data/mn-math.json
server/prisma/seed-data/webwork.json
server/prisma/seed.ts
server/src/model.test.ts
server/src/model.ts
server/src/types.ts

This PR modifies the classification system so that it is no longer a tree. Now, a given classification can belong to multiple subcategories, meaning the same classification can be reached through multiple paths.
When content is assigned one of these classifications, it automatically can be found in all paths leading to that classification.
The classification is currently displayed with multiple categories or subcategories separated by slashes. This works OK for cases where the categories/subcategories are short and only one of category or subcategory differs. When a classification has paths where both category and subcategory differ, the display is confusing (which currently happens only a few times).
Using this feature, we now include the math portion of the webwork taxonomy.

allow a classification to have multiple sub-categories

---

client/cypress/e2e/Explore/navigateExplore.cy.ts
client/cypress/support/commands.ts
client/src/Tools/_framework/Paths/ActivityViewer.tsx
client/src/Tools/_framework/Paths/AssignmentViewer.tsx
client/src/Tools/_framework/Paths/ChangeName.tsx
client/src/Tools/_framework/Paths/CodeViewer.tsx
client/src/Tools/_framework/Paths/Explore.tsx
client/src/Tools/_framework/Paths/SharedActivities.tsx
client/src/Tools/_framework/Paths/SignIn.tsx
client/src/Tools/_framework/Paths/SiteHeader.tsx
client/src/Tools/_framework/ToolPanels/AddContentToMenu.tsx
client/src/Tools/_framework/ToolPanels/CompoundActivityEditor.tsx
server/src/index.ts

This PR stores `currentTab` of `Explore` in the `SiteContext` so that the current tab being displayed is remembered when one navigates back to `Explore`.

remember explore current tab across site

---

client/src/Tools/_framework/Paths/Activities.tsx
client/src/Tools/_framework/Paths/ActivityEditor.tsx
client/src/Tools/_framework/Paths/ActivityViewer.tsx
client/src/Tools/_framework/Paths/Explore.tsx
client/src/Tools/_framework/Paths/Home.tsx
client/src/Tools/_framework/Paths/SharedActivities.tsx
client/src/Tools/_framework/Paths/SiteHeader.tsx
client/src/Tools/_framework/ToolPanels/AuthorModeModal.tsx
client/src/Tools/_framework/ToolPanels/CompoundActivityEditor.tsx
client/src/Tools/_framework/ToolPanels/DeveloperModeModal.tsx
client/src/Widgets/Card.tsx
client/src/Widgets/CardList.tsx
client/src/_utils/types.ts
client/src/index.tsx
server/prisma/migrations/20250403054146_init/migration.sql
server/prisma/migrations/20250404014529_init/migration.sql
server/prisma/schema.prisma
server/src/query/user.ts
server/src/routes/userRoutes.ts
server/src/schemas/userSchemas.ts
server/src/test/folder.test.ts
server/src/test/share.test.ts
server/src/test/users.test.ts
server/src/types.ts

This PR adds an `isAuthor` flag to the user record, which defaults to `false`. The idea is to insulate new users from the DoenetML source code until they turn on author mode.
If `isAuthor` is `false`, then the activity editor and viewer default to view mode for documents, and the edit button displays a message prompting to turn on author mode.  if `isAuthor` is `true`,  the activity editor and viewer default to edit mode.
If `isAuthor` is `false`,  the new document menu items in Activities and the compound activity editor display a message prompting to turn on author mode.

add isAuthor flag to user

---

server/src/index.ts

Fix a regression from #2555 where non-anonymous login using magic link was unauthorized due to missing fields.

Fix regression in magic link login

---

server/package-lock.json
server/package.json

Waiting for `nodemon` to recompile TS files was painfully slow - a handful of seconds on my machine. This package does it faster.
Package change only affects transpiling in development. We still use `tsc` for building.
I've left type-checking on, but we could also enable `--transpile-only` as some people suggest and speed it up even more. It's down to 2 seconds for me, so it's fine for now.

Use `ts-node-dev` to transpile server TS files instead of `nodemon`

---

client/src/paths/ChangeName.tsx
client/src/views/AssignmentInvitation.tsx

Smail front-end tweaks
* Made change name screen responsive
* Invite students page displays link in one line. Ex: `doenet.org/code/01234` rather than `doenet.org/code and type in 01234`

Responsive change name screen

---

client/package-lock.json
client/package.json
client/src/paths/Home.tsx
client/src/views/AssignmentItemResponseStudent.tsx
server/prisma/seed.ts
server/src/test/activity.test.ts
server/src/test/assign.test.ts

This PR changes the answer response menu to a button. Previously, the button opened a popup menu with a link that one had to click to display the answer responses. Now, the extra step of the menu is eliminated, and clicking the button immediately displays a student's responses to that answer blank.
One drawback, given that the attribute on `<DoenetViewer>` changed from `showAnswerResponseMenu` to `showAnswerResponseButton`, is that the button is no longer shown if the authors use a version of DoenetML below `0.7.0-alpha54`.

Answer response menu is a button

---

client/src/drawerTabs/RemixSources.tsx
client/src/drawerTabs/Remixes.tsx
client/src/popups/ConfirmAssignModal.tsx
client/src/types.ts
client/src/types_module_specific.ts
server/src/test/remix.test.ts
server/src/types.ts
server/src/types_module_specific.ts

Re-format the `types.ts` files in server and client so that they are exactly the same. You should be able to copy-and-paste the entire file into the other.
There's a couple types we define differently between the two modules. I moved them into `types_module_specific.ts`.

Types parity between server and client

---

client/src/dropdowns/CreateContentMenu.tsx
client/src/paths/Activities.tsx
client/src/popups/AddContentToMenu.tsx
client/src/views/CompoundActivityEditor.tsx
server/src/query/activity.ts

Remove all the buttons that allow you to add a question bank.
The server still allows creating them. After a while, when we're sure we don't want question banks,
we can remove all and code and tests relating to them.

Remove create question bank button

---

client/src/dropdowns/CreateContentMenu.tsx
client/src/popups/CreateContentAndPromptName.tsx

Fix the button where you create a new problem set or folder with the selected items as children.
Resolves #2629 - silly bug, small fix
Resolves #2602 - ensure create content API is called only once

Fix "Create from selected" button

---

server/src/schemas/rangedNumber.ts

Fix Zod's schema so that it allows the student response page to load.
Zod confined `stringAsRangedNumber` to an integer, but that doesn't work for GET parameters which are inherently strings.
Now it's _coerced_ to an integer.

Fix student response page

---

client/src/popups/MoveCopyContent.tsx

The heading used to display `null` for documents.

Fix move document modal heading

---

client/src/paths/ActivityViewer.tsx

The existing wording is confusing:
What are you adding to?
I changed it to "Sign In To Use Content".

Wording change on activity viewer "sign in" button
